[project]
name = 'robobottom9'
dynamic = ['version']
description = 'RoboBottomV9 Discord Bot as PyPI package for easy deployment'
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "platformdirs==4.10.0",
    "pydantic==2.13.4",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "src/robobottom9/_version.py"
pattern = '__version__(?:: str)? *= *\"(?P<version>[^\"]+)\"'
